# Netlify build configuration for AI Trend Digest
# This version tells Netlify to simply serve the already-built /site folder
# that the GitHub Action commits each day — no OpenAI keys needed on Netlify.

[build]
  publish = "site"
  command = "echo 'Serving prebuilt site'"

[build.environment]
  NODE_VERSION = "20"

# Optional: set headers or redirects here if you want
# Example security headers:
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "interest-cohort=()"
    Cache-Control = "public, max-age=3600"

# Optional redirect to make root domain work
[[redirects]]
  from = "https://www.your-site.netlify.app/*"
  to = "https://your-site.netlify.app/:splat"
  status = 301
  force = true
